name: Dependency Security Scan

on:
  pull_request:
    paths:
      - '**/pom.xml'
      - 'pom.xml'

jobs:
  security:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      security-events: write
    timeout-minutes: 15

    steps:
      - uses: actions/checkout@v4
      - name: Dependency Review
        uses: actions/dependency-review-action@v4.6.0
        with:
          vulnerability-check: true
