name: Dependency Security Scan

on:
  pull_request:
    paths:
      - '**/pom.xml'
      - 'pom.xml'

jobs:
  security:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      security-events: write
    timeout-minutes: 15  # Add timeout to prevent hung jobs

    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 11
        uses: actions/setup-java@v4
        with:
          java-version: '11'
          distribution: 'corretto'
          cache: maven
        id: setupjava

      - name: OWASP Dependency Check
        uses: dependency-check/Dependency-Check_Action@main
        env:
          JAVA_HOME: ${{ steps.setupjava.outputs.path }}
        with:
          project: 'Amazon MQ Samples Project'
          path: '.'
          format: 'SARIF'  # Changed to SARIF for better GitHub integration
          args: >
            --enableExperimental
            --failOnCVSS 7

      - name: Upload SARIF file
        uses: github/codeql-action/upload-sarif@v3
        if: always()
        with:
          sarif_file: ${{github.workspace}}/dependency-check-report.sarif
