name: Dependency Security Scan

on: [pull_request]

jobs:
  security:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 11
        uses: actions/setup-java@v4
        with:
          java-version: '11'
          distribution: 'corretto'
          cache: maven

      - name: OWASP Dependency Check
        uses: dependency-check/Dependency-Check_Action@main
        with:
          project: 'Amazon MQ Samples Project'
          path: '.'
          format: 'HTML'
          out: 'reports'
          args: >
            --enableExperimental
            --failOnCVSS 7
            --suppressionFile suppression.xml

      - name: Upload Dependency Check Report
        uses: actions/upload-artifact@v4
        if: always()  # This ensures the report is uploaded even if the scan fails
        with:
          name: dependency-check-report
          path: ${{github.workspace}}/reports
